name: option_trade_aggs
language: python
variables:
  - name: INPUT
    inputType: InputTopic
    defaultValue: option-trades
    required: false
  - name: OUTPUT
    inputType: OutputTopic
    defaultValue: option-trade-aggs
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
