name: option_trade_aggs
language: python
variables:
  - name: INPUT
    inputType: InputTopic
    defaultValue: option-trades
    required: false
  - name: OUTPUT
    inputType: OutputTopic
    defaultValue: option-trade-aggs
    required: false
  - name: KAFKA_PASSWORD
    inputType: Secret
    defaultValue: KAFKA_PASSWORD_key
    required: false
  - name: BOOTSTRAP_SERVERS
    inputType: FreeText
    defaultValue: csdv607229g095ngiqrg.any.us-east-1.mpx.prd.cloud.redpanda.com:9092
    required: false
  - name: SASL_MECHANISM
    inputType: FreeText
    defaultValue: SCRAM-SHA-256
    required: false
  - name: SECURITY_PROTOCOL
    inputType: FreeText
    defaultValue: SASL_SSL
    required: false
  - name: SASL_USERNAME
    inputType: FreeText
    defaultValue: admin
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
