CREATE TABLE option_trades (
  osym string,
  usym string,
  expiry date,
  ts timestamp(9),
  buy_vol int,
  sell_vol int,
  mid_vol int,
  stock_vol int,
  nsd_vol int,
  vol int,
  oi int,
  qty int,
  price double,
  theo double,
  iv double,
  delta double,
  gamma double,
  theta double,
  vega double,
  rho double,
  bid double,
  ask double,
  dtx int,
  strike double,
  id string,
  otype string,
  premium double,
  side string,
  sentiment string,
  cond string,
  xchg string,
  spot double,
  leg_vol int,
  tags array<string>,
  size_class string,
  score double default 0,
  _timestamp timestamp,
  _key string)
LOCATION 's3://tradesignals-db/option_trades'
TBLPROPERTIES (
  'table_type'='iceberg',
  'write_compression'='SNAPPY',
  'format'='iceberg'
);