name: option_trades
language: Python
variables:
  - name: OUTPUT
    inputType: OutputTopic
    defaultValue: option-trades
    required: false
  - name: UNUSUALWHALES_TOKEN
    inputType: Secret
    defaultValue: UNUSUALWHALES_TOKEN_key
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
