name: option_trades
language: Python
variables:
  - name: OUTPUT
    inputType: OutputTopic
    defaultValue: option-trades
    required: false
  - name: UNUSUALWHALES_TOKEN
    inputType: Secret
    defaultValue: UNUSUALWHALES_TOKEN_key
    required: false
  - name: WHALE_PREMIUM_THRESHOLD
    inputType: FreeText
    defaultValue: 75000
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
