[project]
name = "option_trades"
version = "1.0.0"
description = "Produces to option-trades kafka topic."
readme = "README.md"
requires-python = ">=3.12"

[tool.uv.sources]
common = { workspace = true }