name: news
language: python
variables:
  - name: OUTPUT
    inputType: OutputTopic
    defaultValue: news
    required: false
  - name: POLYGON_API_KEY
    inputType: Secret
    defaultValue: POLYGON_API_KEY_key
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
