name: equity_quotes
language: Python
variables:
  - name: OUTPUT
    inputType: OutputTopic
    defaultValue: equity-quotes
    required: false
  - name: POLYGON_TOKEN
    inputType: Secret
    defaultValue: POLYGON_TOKEN_key
    required: false
  - name: WEBSOCKET_ENDPOINT
    inputType: FreeText
    defaultValue: wss://delayed.polygon.io/stocks
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
