name: equity_quotes
language: Python
variables:
  - name: OUTPUT
    inputType: OutputTopic
    defaultValue: equity-quotes
    required: false
  - name: SASL_PASSWORD
    inputType: Secret
    defaultValue: SASL_PASSWORD_key
    required: false
  - name: POLYGON_TOKEN
    inputType: Secret
    defaultValue: POLYGON_TOKEN_key
    required: false
  - name: SASL_USERNAME
    inputType: FreeText
    defaultValue: api-service
    required: false
  - name: SASL_MECHANISM
    inputType: FreeText
    defaultValue: SCRAM-SHA-256
    required: false
  - name: SECURITY_PROTOCOL
    inputType: FreeText
    defaultValue: SASL_SSL
    required: false
  - name: BOOTSTRAP_SERVERS
    inputType: FreeText
    defaultValue: csdv607229g095ngiqrg.any.us-east-1.mpx.prd.cloud.redpanda.com:9092
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
