name: mlearn_options_data
language: python
variables:
  - name: INPUT
    inputType: InputTopic
    defaultValue: option-trade-aggs
    required: false
  - name: OUTPUT
    inputType: OutputTopic
    defaultValue: mlearn-options-data
    required: false
  - name: MODEL_NAME
    inputType: FreeText
    defaultValue: my_model
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
