name: option_trades_sink
language: Python
variables:
  - name: INPUT
    inputType: InputTopic
    defaultValue: option-trades
    required: false
  - name: AWS_SECRET_ACCESS_KEY
    inputType: Secret
    defaultValue: AWS_SECRET_ACCESS_KEY_key
    required: false
  - name: AWS_ACCESS_KEY_ID
    inputType: Secret
    defaultValue: AWS_ACCESS_KEY_ID_key
    required: false
  - name: KAFKA_SECRET
    inputType: Secret
    defaultValue: KAFKA_SECRET_key
    required: false
  - name: AWS_S3_URI
    inputType: FreeText
    defaultValue: s3://tradesignals-db/option_trade_data
    required: false
  - name: TABLE_NAME
    inputType: FreeText
    defaultValue: tradesignals_db.option_trade_data
    required: false
  - name: AWS_REGION
    inputType: FreeText
    defaultValue: us-east-1
    required: false
  - name: KAFKA_KEY
    inputType: FreeText
    defaultValue: admin
    required: false
  - name: KAFKA_BROKER_ADDRESS
    inputType: FreeText
    defaultValue: csdv607229g095ngiqrg.any.us-east-1.mpx.prd.cloud.redpanda.com:9092
    required: false
  - name: KAFKA_SASL_MECHANISM
    inputType: FreeText
    defaultValue: SCRAM-SHA-256
    required: false
  - name: KAFKA_SECURITY_PROTOCOL
    inputType: FreeText
    defaultValue: SASL_SSL
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
